language: scala
scala:
   - 2.10.5
   - 2.11.7
jdk: oraclejdk7
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/545214825034815158da
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false